version: '2'
services:
  web:
    image: webdevops/php-nginx:7.1
    volumes:
      - .:/app
      - ./docker/nginx/vhost.common.d/vhost.common.conf:/opt/docker/etc/nginx/vhost.common.d/10-location-root.conf
    links:
      - redis
    environment:
      - WEB_DOCUMENT_ROOT=/app/web
    ports:
      - "127.0.0.1:80:80"   # Access Packages in your browser at http://127.0.0.1:80
      - "127.0.0.1:443:443" # Access Packages in your browser at https://127.0.0.1:443
  redis:
    image: redis:3.2
    expose:
      - "6379"
